server:
  port: ${PORT:8080}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

jwt:
  secret-key: ${JWT_SECRET_KEY:devDefaultKeyForLocalOnly1234567890123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:PT2H}

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://dpg-d2dl253uibrs739qq5f0-a.oregon-postgres.render.com/expenses_rn6n
    username: expenses_rn6n_user
    password: fPSeoKfjW49koKsukyCttW8lRxSopOOt
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    com.rodolfocf: INFO
    org.hibernate: WARN
    org.springframework.security: INFO
