
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expenses_db
    username: postgres
    password: 9951
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update


# ? Chave JWT carregada do ambiente
jwt:
  secret-key: ${JWT_SECRET_KEY:devDefaultKeyForLocalOnly1234567890123456789012345678901234567890}
  expiration: PT2H


