server:
  port: ${PORT:8080}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# Configuração do JWT
jwt:
  secret-key: ${JWT_SECRET_KEY:devDefaultKeyForLocalOnly1234567890123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:PT2H}

---
# Perfil de desenvolvimento (local)
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/expenses_db
    username: postgres
    password: 9951
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

---
# Perfil de produção (Render)
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

# Swagger/OpenAPI (funciona em ambos os perfis)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    com.rodolfocf: INFO
    org.hibernate: WARN
    org.springframework.security: INFO